# Generated by Django 6.0.3 on 2026-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField()),
                ('prediction', models.CharField(max_length=255)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein', models.CharField(blank=True, max_length=50, null=True)),
                ('avoid', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
