# Generated by Django 6.0.3 on 2026-04-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealhistory',
            name='food_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='meal_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='trigger_foods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
