# Generated by Django 6.0.3 on 2026-04-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mealhistory_food_allergy_mealhistory_meal_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealhistory',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='diet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='exercise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mealhistory',
            name='risk',
            field=models.CharField(default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='mealhistory',
            name='avoid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
