# Generated by Django 6.0.4 on 2026-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile_allergies_userprofile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(max_length=50)),
                ('meal_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('calories', models.IntegerField()),
                ('protein', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
