# Generated by Django 6.0.4 on 2026-04-26 14:26

from django.db import migrations


def seed_data(apps, schema_editor):
    MealPlan = apps.get_model('api', 'MealPlan')
    ExercisePlan = apps.get_model('api', 'ExercisePlan')
    
    # Check if already seeded to prevent duplicates
    if not MealPlan.objects.exists():
        meals = [
            # Muscle Gain
            {"goal": "muscle", "type": "Breakfast", "name": "Oatmeal with Protein Powder", "cal": 450, "pro": "35g", "img": "https://images.unsplash.com/photo-1517673132405-a56a62b18caf?auto=format&fit=crop&w=500&q=60"},
            {"goal": "muscle", "type": "Lunch", "name": "Grilled Chicken Rice Bowl", "cal": 600, "pro": "45g", "img": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=500&q=60"},
            {"goal": "muscle", "type": "Dinner", "name": "Steak with Sweet Potato", "cal": 550, "pro": "40g", "img": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=500&q=60"},
            
            # Lose Weight
            {"goal": "lose", "type": "Breakfast", "name": "Egg White Scramble", "cal": 250, "pro": "20g", "img": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=500&q=60"},
            {"goal": "lose", "type": "Lunch", "name": "Tuna Salad", "cal": 350, "pro": "30g", "img": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=500&q=60"},
            {"goal": "lose", "type": "Dinner", "name": "Baked Salmon with Asparagus", "cal": 400, "pro": "35g", "img": "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=500&q=60"},
            
            # General
            {"goal": "general", "type": "Breakfast", "name": "Fruit Smoothie Bowl", "cal": 300, "pro": "10g", "img": "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?auto=format&fit=crop&w=500&q=60"},
            {"goal": "general", "type": "Lunch", "name": "Quinoa Salad", "cal": 400, "pro": "15g", "img": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=500&q=60"},
            {"goal": "general", "type": "Dinner", "name": "Chicken Stir Fry", "cal": 450, "pro": "25g", "img": "https://images.unsplash.com/photo-1604908176997-4319c50c2e35?auto=format&fit=crop&w=500&q=60"}
        ]
        
        for m in meals:
            MealPlan.objects.create(
                goal_type=m["goal"],
                meal_type=m["type"],
                name=m["name"],
                calories=m["cal"],
                protein=m["pro"],
                image_url=m["img"]
            )
            
    if not ExercisePlan.objects.exists():
        exercises = [
            # Muscle Gain
            {"goal": "muscle", "name": "Bench Press", "sets": "4 sets of 8-10 reps", "img": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=500&q=60"},
            {"goal": "muscle", "name": "Squats", "sets": "4 sets of 8-12 reps", "img": "https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?auto=format&fit=crop&w=500&q=60"},
            {"goal": "muscle", "name": "Deadlifts", "sets": "3 sets of 5-8 reps", "img": "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=500&q=60"},
            
            # Lose Weight
            {"goal": "lose", "name": "HIIT Treadmill", "sets": "20 mins", "img": "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=500&q=60"},
            {"goal": "lose", "name": "Jump Rope", "sets": "15 mins", "img": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=500&q=60"},
            {"goal": "lose", "name": "Bodyweight Circuit", "sets": "3 rounds", "img": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=500&q=60"},
            
            # General
            {"goal": "general", "name": "Yoga Flow", "sets": "30 mins", "img": "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=500&q=60"},
            {"goal": "general", "name": "Light Jogging", "sets": "25 mins", "img": "https://images.unsplash.com/photo-1552674605-db6afe4b153b?auto=format&fit=crop&w=500&q=60"},
            {"goal": "general", "name": "Core Stretching", "sets": "15 mins", "img": "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=500&q=60"}
        ]
        
        for ex in exercises:
            ExercisePlan.objects.create(
                goal_type=ex["goal"],
                name=ex["name"],
                sets=ex["sets"],
                image_url=ex["img"]
            )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
