# Generated by Django 6.0.4 on 2026-04-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20260426_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
