# Generated by Django 6.0.2 on 2026-02-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='allergyrecord',
            options={'verbose_name': 'Allergy Record', 'verbose_name_plural': 'Allergy Records'},
        ),
        migrations.AlterModelOptions(
            name='symptom',
            options={'verbose_name': 'Symptom', 'verbose_name_plural': 'Symptoms'},
        ),
    ]
